### ISSUE TITLE
Service automatically Deregister

### ISSUE THREAD

**Issue by donch** [cloudwatt/kube2consul#1]
Hi, 

I'm testing this bridge between k8s and consul and i have something weird.

My consul k8s service flap and go through register/deregister state.

Here is a sample of logs from the consul container : 

`2016/09/06 09:29:56 [INFO] agent: Deregistered service 'consul-svc3'`
`2016/09/06 09:31:09 [INFO] agent: Deregistered service 'consul-svc3'`

It seems to be caused by the use of CatalogApi instead of AgentAPI of consul. 

There is an explanation here : https://github.com/hashicorp/consul/issues/1188#issuecomment-185977469

This explanation make sense ? Have you got the same behavior on your side ?

**Comment by lightcode** [comment]
Hi,

I never have seen that problem. Can you tell me what version of Consul have you used?

I will try to reproduce your problem.

**Comment by donch** [comment]
Hi @lightcode , 

My current version of consul is Consul v0.5.2
kube2consul v1.0.1

Thanks for your support, let me know if your need further informations.

**Comment by lightcode** [comment]
Hi @donchh,

I can't reproduce your issue. Could you upgrade Consul in 0.6.4 and try kube2consul with this version? Also, can you post kube2consul logs (please add `--v=2` to increase verbose).
